HL7/fhir-ig-publisher

- org.hl7.fhir.publisher.core/.classpath
- org.hl7.fhir.publisher.core/.project
> Correct dependencies to not be specific to Grahame's harddrive

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/templates/TemplateManager.java
Give a warning when not executing scripts
> Allow scripts to be executed independently of base directory

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/IGKnowledgeProvider.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/ValidationPresenter.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/templates/Template.java
Fixed problem where onGenerate action wasn't getting IG changes
> Fixed problem with dependency id logic

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/CqlSubSystem.java
Added support for parameters.
Fixed an issue with data requirement generation
Tested on sample-ig, sample-content-ig, and opioid-mme-r4
> Added support for model, code system and value set dependencies.

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/AdjunctFileLoader.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/CqlSubSystem.java
Added support for translator options for CQL
Verified functional with sample-ig, sample-content-ig, and opioid-mme-r4
> Improved parameter handling and conformance checking for CQL libraries.

- pom.xml
Will it blend? That is the question.
> Can azure pipelines build this?

- RELEASE_NOTES.md
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/SpecMapManager.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/templates/TemplateManager.java
> issues for 1.1.20 release

- RELEASE_NOTES.md
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/SimpleFetcher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGReleaseUpdater.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGReleaseVersionUpdater.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGWebSiteMaintainer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IndexMaintainer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/PublicationProcess.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/BaseRenderer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/CanonicalRenderer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/CodeSystemRenderer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/QuestionnaireRenderer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StatusRenderer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureMapRenderer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/ValueSetRenderer.java
- pom.xml
> library rendering

- RELEASE_NOTES.md
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/VersionCheckRenderer.java
- pom.xml
* Fix bug generating table-profiles.xhtml
> * Fix bug trying to read package-list.json

- RELEASE_NOTES.md
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/PublicationProcess.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/ValidationPresenter.java
* WebSite Manager: fix problem publishing history when publishing a new IG for the first time
> * QA: Fix NPE when IG is not an HL7 IG

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/FetchedResource.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/templates/Template.java
Ensure we don't publish Provenance and Provenance bundles that represent history of other resources as resource pages
> No history publish

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/templates/Template.java
Changes needed to allow next/prev links in an IG.  These changes ensure that the 'pages' JSON file is complete, includes only those pages that are actually displayed in an IG and are listed in the order they appear within the IG - including sub-tabs within resource pages.
> Added needed support for proper next/prev links in IGs.

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
See https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Extension.20examples
> Clarify "not used in this Implementation Guide" is about profiles

- RELEASE_NOTES.md
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/PublisherLoader.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/BaseRenderer.java
- pom.xml
Updates this project to match the changes in this PR: https://github.com/hapifhir/org.hl7.fhir.core/pull/635
> Refactor to match core convertor_refactor_III

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGWebSiteMaintainer.java
Fixes #336 by adding a -noprompt command line argument
> add -noprompt arg for release updater

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
It wasn't immediately obvious to a FSH beginner that the line should go into the yaml config.
> Clarify jurisdiction message for FSH

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
Fixes for handling 2-character country codes
> Fmm propagation and contained support

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/WebSiteLayoutRulesProviders.java
Sorry, I left out the www in the previous PR. I'm told these are the correct URLs
> fix one more issue with Belgian URLs

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
https://github.com/HL7/fhir-ig-publisher/issues/138
> add -v option to display version number

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
ISSUE: https://github.com/HL7/fhir-ig-publisher/issues/429.
There are production content IGs that require Jekyll processing that exceeds the 5 minute default. Allow the value to be configured.
> Add the ability to configure the timeout for jekyll

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/DependentIGFinder.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/PreviousVersionComparator.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/FeedBuilder.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGCategorizer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGPackageChecker.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGRegistryMaintainer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGReleaseRedirectionBuilder.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGReleaseUpdater.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGReleaseVersionDeleter.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IndexMaintainer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/PackageReleaser.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/PublicationProcess.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/TemplateReleaser.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/DependencyRenderer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/VersionCheckRenderer.java
- pom.xml
This brings the core version up to date.
In the process it resolves issues caused by the refactoring of JSONUtil/JsonUtilities and Utilities
Note: https://github.com/hapifhir/org.hl7.fhir.core/pull/843 must be merged before this PR can be merged.
> Update core version + fix JSONUtil + fix presentDuration

- pom.xml
Ensures that Apache POI versions will stay in sync
> Use property for apache poi versions

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/comparators/IpaComparator.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/comparators/PreviousVersionComparator.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/realm/USRealmBusinessRules.java
- pom.xml
Fix for changes made in this core PR:
https://github.com/hapifhir/org.hl7.fhir.core/pull/864
> Don't access getBinaries directly in XVerExtensionManager

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/templates/Template.java
- pom.xml
See https://github.com/hapifhir/org.hl7.fhir.core/pull/919
> When converting to r4 ImplementationGuide, use produceIllegalParameters

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/PublicationProcess.java
@grahamegrieve can you please review?
> always use absolute path for rdestination

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
Revamped code to generate improved diffs and allow tab-based representation of terminology, constraints and data dictionary
https://github.com/HL7/fhir-ig-publisher/issues/222
https://github.com/HL7/fhir-ig-publisher/issues/327
> Ig rendering changes

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/HTMLInspector.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
Change help link for SD tables, add help link for data dictionaries
> Fix dict issues

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/web/WebSiteLayoutRulesProviders.java
> support for HL7 EU IG package names

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/templates/TemplateManager.java
> allow liquid files in template

- checkstyle.xml
- org.hl7.fhir.publisher.cli/checkstyle_suppressions.xml
- org.hl7.fhir.publisher.core/checkstyle_suppressions.xml
- pom.xml
This enables checkstyle for the build with some basic style checks.
> Enable checkstyle for build

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/HTMLInspector.java
Fixes path character based exceptions in HTMLInspector when run for RAD.IRA IG
> Fix another windows char issue

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
This adds the `-fhir-settings` param to initialize FhirSettings from a file instead of default or a Java system property.
It also removes dead code for `-api-key-file` and one unused field.
> Add -fhir-settings param 

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/SpecialTypeHandler.java
Additional update to include TestPlan in prior FHIR versioned IGs
Related to: [#618](https://github.com/HL7/fhir-ig-publisher/issues/618)
> #618 Additional update to include TestPlan in prior FHIR versioned IGs

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/FSHRunner.java
Fixes to FSH command execution have broken functionality. This is a temporary revert to get auto IG builds running once more.
> Revert FSH changes

- build-and-exec-jobs-template.yml
- pull-request-pipeline.yml
Adds Mac and Windows exec pipelines
> Add more OS support for exec pipeline

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
Adds a param `-package-cache-folder` to explicitly set the package cache folder.
> Add package cache folder param

- .azure/plot-ig-builder-auto/plot-ig-builder-auto.py
- master-branch-pipeline.yml
- master-branch-plot-pipeline.yml
Adds the following script to a pipeline that runs parallel to the master build pipeline:
https://github.com/djvreeman/hl7-standards-dev-data/blob/main/scripts/plot-ig-builder-auto.py
This updates the following file in the GitHub repository: https://github.com/HL7/fhir-ig-publisher/blob/master/plot-ig-builder-auto.png
> Plot builder pipeline

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/DependentIGFinder.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/IGPack2NpmConvertor.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/R4ToR4BAnalyser.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/comparators/ImposesComparator.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/comparators/IpaComparator.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/comparators/IpsComparator.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/comparators/PreviousVersionComparator.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/realm/USRealmBusinessRules.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/CrossVersionOIDScanner.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGCategorizer.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/PackagCanonicalClashDetector.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/PackageReleaser.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/xig/XIGGenerator.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
Uses refactor to  Builder construction for FilesystemPackageCacheManger
> Changes to match FilesystemPackageCacheManager refactor

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/templates/TemplateManager.java
see discussion in https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Trusted.20Template.20Process for additional information.
email informing committer/grahame about process has be done
> add ch.fhir.ig.template as trusted

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/SimpleFetcher.java
> do not add Binary resources which are not really Binary #910

- README.md
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/modules/CrossVersionModule.java
Also update the readme to explain how to debug with vs-code
> Ensure the xver-qa temp folder exists before trying to write/read files from the folder

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/loaders/AdjunctFileLoader.java
> Add Gherkin, json, xml, and text to AdjunctFileLoader.java

- pom.xml
> Bump apache poi to 5.4.0

- nightly-xig-pipeline.yml
This runs all of the XIG pipeline using a single step with a longer timeout.
> Run XIG pipeline in one step

- .github/workflows/owasp.yml
- pom.xml
This workflow now runs without 401 errors: https://github.com/HL7/fhir-ig-publisher/actions/runs/18164423457/job/51702765153
> Fix OWASP workflow
