- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/FetchedFile.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/FetchedResource.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
For many resource types there isn't a description column and these will then just default in the name of the resource again (or the Id). Instead of doing this, leverage the name that is provided by the Implementation Guide
Also:
* close the file stream when processing the transaction log output
* create a new output snippit - table format of the examples list
* the title used when a fetched resource doesn't have one was changed from `type(space)id` to a normal resource reference `type/id`
> Improve rendering of tables and include an examples table as an optional output (take2)

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
Correct the spelling of the word "version" (misspelled as "vesion").
> Fix spelling error in publish box text.

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
this pull requests updates the ig publisher to use for logical models and structure definitions with derivation type specialization the snapshot generation functionality ([see merged pull request which introduced this functionality in org.hl7.fhir.core](https://github.com/hapifhir/org.hl7.fhir.core/pull/90))
> use snapshot generation for logical/specialization

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/ValidationServices.java
The processing code assumed that canonical-based URLs would have multiple parts after the canonical base.  When resources mistakenly didn't follow this pattern, the publisher would crash.  Now it checks the length of the split array before trying to index into it.  The invalid URL is then captured and logged further down the processing chain and correctly flagged as an invalid URL.
**TO TEST:**
Create or edit a profile so that the binding valueset URL points to a URL that starts w/ FHIR canonical, but is not a proper `ValueSet` defining url.  For example: `http://hl7.org/fhir/valueset-languages.html` (instead of the proper `http://hl7.org/fhir/ValueSet/languages`).  _NOTE: I've seen folks make this mistake several times before._
**BEFORE THIS CHANGE:**
When you run the IG Publisher, you …
> Guard against crashes when canonical-based URLs are invalid

- pom.xml
Set source to Java 8 for the maven-javadoc-plugin to fix a javadoc error when building from the command line.
> Fix javadoc error on command line build

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/ValidationPresenter.java
Not sure if this bit of code is used, but don't think the old url is needed there
> Update link to download latest IG Publisher in ValidationPresenter

- org.hl7.fhir.publisher.core/pom.xml
Updates CQL translator dependency to latest 1.5 snapshot. Tested and verified with sample-ig and sample-content-ig implementation guides.
> Updated CQL translator dependency to 1.5.0-SNAPSHOT

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/HTLMLInspector.java
This is just to make the code "safer" by avoiding a crash when there are headings with no text. Perhaps the rendering can avoid it altogether, or a warning message could be produced, but this should not crash the publisher.
(sorry if coding is poor)
> Avoid fatal crash due to issue #236

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/ValidationServices.java
Addresses Issue# 103 - Fixes a nullReferenceException that results from validation of a Bundle with entries that have no fullUrl.
> Issue#103 - Fixed NRE in Bundle validation for entries with no fullUrl

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
npm package list wasn't being updated after importing a new package - which is what happens every time on the CI build. As a result, example resolution wasn't checking against those imported packages. Moved the point of adding the package to the list post-import. (If there's a reason why the adding to the list was happening post-import, then need to find some other way of ensuring that examples are de-referenced properly by the validator.)
> Reverted unintended commits and just fixing the SDC example import issue

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
[Citation](https://build.fhir.org/citation.html) is a MetadataResource and hence must be added to `metadataResourceNames` in order for the IG publisher to work with that resource.
> added Citation to metadataResourceNames

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
ISSUE: https://github.com/HL7/fhir-ig-publisher/issues/427
The following message is very confusing in the case of a watchdog timeout:
"Note: Check that [launched process] is installed correctly."
Since the actual case is known, log it.
> When a watchdog process times-out, log a timeout.

- pom.xml
The Apache POI dependencies must all share the same version, or else there will be class incompatibilities at runtime, like the following:
```shell
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:497)
at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1489)
at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:242)
at org.hl7.fhir.r5.renderers.spreadsheets.SpreadsheetGenerator.finish(SpreadsheetGenerator.java:78)
at org.hl7.fhir.igtools.publisher.Publisher.generateOutputsStructureDefinition(Publisher.java:9459)
at org.hl7.fhir.igtools.publisher.Publisher.generateResourceHtml(Publisher.java:8348)
at …
```
> Update skipped apache poi dependencies

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
during the go-publish process we got invalid temp file paths (_includes/ncludes/):
```
Exception generating page /var/folders/s7/jwn3pbfn70q5n61gxn3p92m80000gn/T/ch-core/temp/pages/_includes/ncludes/logo.html for _includes/ncludes/logo.html in /var/folders/s7/jwn3pbfn70q5n61gxn3p92m80000gn/T/ch-core/temp/pages: /var/folders/s7/jwn3pbfn70q5n61gxn3p92m80000gn/T/ch-core/temp/pages/_includes/ncludes/logo.html
```
it appears that the getPath functions returns sometime /private/var/folders/... instead of /var/folders/... and this provoked the above invalid subtraction. in this PR we check for that problem and correct this edge case
> osx /var and and /private/var

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/WebSiteLayoutRulesProviders.java
we have a swiss specific hl7 convention for package naming and publication, if we want to use -go-publish we have the need to add this specific naming rules: 
package name: ch.fhir.ig.[code]#version
canonical: http://fhir.ch/ig/[code]/version
realm: ch
see also https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/NPM.20package.20name
> add fhir.ch namingrulesprovider

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- pom.xml
This PR requires that org.hl7.fhir.core 5.6.68 is released and will fail all checks until it is.
> Add warning if file encoding isn't UTF-8

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/xig/XIGGenerator.java
The -xig option in the Publisher jar instantiated XIGGenerator, but didn't actually execute it.
> Enable -xig execution from Publisher jar

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
Update the SNOMED CT and LOINC text in the getCopyRightStatement() function, and add a strip() statement to the stripPara() function logic so that the ending '\</p\>' suffix is detected and removed.
> Fix malformed html produced for the ip-statements.xhtml fragment.

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/xig/XIGRenderer.java
- pom.xml
Some packages contain content that can throw exceptions in the XIGRenderer renderResource(...) method.
This catches and reports those exceptions with additional information about the resource that caused them.
> Catch xig render exceptions

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/FetchedResource.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
Add logic that links TestScript resources to Profiles (StructureDefinitions).
The FHIR community has been increasingly interested in provided better support for testing artifacts within IGs. This additional logic is an initial enhancement that allows IGs generated from the HL7 IG template to incorporate and list TestScript resources with their associated FHIR Profiles (StructureDefinitions).
Minor code additions to two (2) classes that provide the needed links between TestScripts and StructureDefinitions:
* **FetchedResource** 
* New List\<String\> variable **testProfiles** to hold the canonical url(s) of the FHIR Profile(s) referenced in a TestScript resource; along with corresponding getter and setter methods
* New HashSet\<FetchedResource\> variable **foundTestScripts** to hold the …
> Add logic to link TestScripts and Profiles

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
Add logic to generate TestScript list and table html fragments for Profiles (StructureDefinitions).
Minor code additions to two (2) classes that provide the needed functionality to generate the TestScript html fragments for StructureDefinitions:
* **StructureDefinitionRenderer** 
* New method **testscriptList()** to generate the TestScript list html fragment
* New method **testscriptTable()** to generate the TestScript table html fragment
* **Publisher**
* **generateOutputsStructureDefinition()** method - new logic modeled after example list and table generation to conditionally call the new **StructureDefinitionRenderer** class methods **testscriptList()** and **testscriptTable()** based on the template config settings **testscript-list** and **testscript-table**.
> Add testscript fragment rendering to StructureDefinitions

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/PublicationChecker.java
A null-pointer exception occurs if exception does not contain a message. This can happen for example if retrieval was successful, but package-list.json is not parseable as a json file.
Specific scenario is an unpublished IG where the canonical url leads to a web server that has a default redirect to a html page.
> NPE in PublicationChecker.checkFolder

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
Sushi logs are trimmed on both sides in MySushiHandler. This leads to removing part of ANSI escape codes used for output coloring and removing indentation of some lines (e.g. when an error arises, Sushi idents the lines "File", "Line", "Applied" for better readability). The logs should only be right-trimmed (to remove \r\n).
Before:
After:
> Sushi: only right-trim logs to increase readability

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
This fixes two issues with the logic for applying the `--require-latest` flag to SUSHI:
1. It adds the missing `" "` (space) between the command and the flag. Prior to this fix, the cmd would contain `fsh-sushi@2.8.0--require-latest` instead of `fsh-sushi@2.8.0 --require-latest`.
2. It applies the flag whether or not `fsh.ini` is used to specify a version. Prior to this fix, it only applied the flag when a version was specified in `fsh.ini`. I don't think this was the intent.
I'd also like to propose relaxing use of `--require-latest` in CI builds. Sometimes setting a specific version is helpful to avoid a recently introduced breaking change or to use a beta version of FSH before it is released. I think it's reasonable for projects to use this in CI up until they're ready for publication. …
> Fix SUSHI require-latest logic

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/HTMLInspector.java
Utilities.path constructs java Path instances to ensure that Paths aren't doing anything nefarious, but the two instances here construct 'kinda' paths with filesystem paths that have anchors ('C:/myig/somefile.html#extension:somethingelse') which can contain illegal characters in the Windows OS. 
Utilities.path should have a way to deal with this, but until then, this works around it.
> Fix HTMLInspector paths that fail in Windows

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/GitUtilities.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/test/java/org/hl7/fhir/igtools/publisher/GitUtilitiesTests.java
Fix for https://github.com/HL7/fhir-ig-publisher/issues/634
Using git worktree created directories was not working correctly with ig publisher. This swaps out the logic by which we get git branch with a more robust and straightforward command.
> Fix github branch name retrieval

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/templates/TemplateManager.java
When a template is a URL, it will resolve as a path under Linux/Max filesystems, but will break in Windows.
This skips attempting to check URLs as possible local directories when loading a template.
> Prevent checks for URL templates as directories

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/FetchedResource.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
Add logic that links TestPlan resources to Profiles (StructureDefinitions).
The FHIR community has been increasingly interested in provided better support for testing artifacts within IGs. This logic is an additional enhancement that allows IGs generated from the HL7 IG template to incorporate and list TestPlan resources with their associated FHIR Profiles (StructureDefinitions).
* [#618](https://github.com/HL7/fhir-ig-publisher/issues/618)
> #618 Add TestPlan to IG Testing Artifacts

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
The R5 condition was duplicated. Fixes e1d61c4.
> Fix typo in R6 support

- .gitignore
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
If we suppress mappings that are all empty - then the `-maps-diff` HTML fragment will contain only the mappings that you've added in your differential. 
Make use of custom template to use `-maps-diff` rather than `-map` HTML fragment gets a much more useful Mappings tab in the StructureDefinition.
While I'm here, I made the `comment` column a markdown field.
> Suppress mappings that are totally empty

- pom.xml
The older jetbrains annotations dependency in okhttp3 contained a pom with http instead of https, which some vulnerability scans flag as an issue.
> Fix older jetbrains annotations transitive dependency

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/ValidationPresenter.java
See issue #675 
This change will create an additional QA file that contains the messages from the IG creation in ESLint-compact format. The file that is created in this eslint-compact format works with 3rd party tooling like vscode problemmatchers, like: $eslint-compact.
Thanks in advance.
> Request IG QA output in eslint-compact format.

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/FSHRunner.java
- org.hl7.fhir.publisher.core/src/test/java/org/hl7/fhir/igtools/publisher/FSHRunnerTests.java
- pom.xml
Command execution should use CommandLine to construct arguments rather than concatenating Strings
> Fix FSHRunner command execution

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/SpecMapManager.java
SpecMapManager is running a special case check for files in DICOM, but asks for some filenames invalid in Windows.
> Fix invalid filename path check in DICOM

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/HTMLInspector.java
urns are being treated as files by checkResolveLink, which creates issues in Windows, where ":" is an illegal character.
Example:
```log
java.nio.file.InvalidPathException: Illegal char <:> at index 28: c:\FHIR-us-pq-cmc\output\urn:uuid:c503d743-ddf4-4dea-9a97-c65a20c1274e
```
> Add urn prefix to rref special cases in HTMLInspector.checkResolveLink

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/web/PackageRegistryBuilder.java
- org.hl7.fhir.publisher.core/src/test/java/org/hl7/fhir/igtools/web/PackageRegistryBuilderTest.java
- org.hl7.fhir.publisher.core/src/test/resources/package-registry/missing-path/package-registry.json
If an entry in package-registry.json is missing a path entry, throw an exception with a meaninful message instead of a  NullPointer.
> Catch missing path entry in package-registry.json

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/HTMLInspector.java
Checks very specifically for invalid paths causing breakages in link evaluation.
> Catch invalid paths in HTMLInspector

- org.hl7.fhir.publisher.core/pom.xml
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/CqlSubSystem.java
This PR updates the CqlSubsystem to use the latest release of the CQL-to-ELM translator, version 3.3.2. This update was tested with the sample-ig and sample-content-ig implementation guides and confirmed that it functions correctly. This update addresses issues with resolving references to FHIRHelpers and FHIR ModelInfo, as well as some improvements to the output of the Library refresh. Note that this update does not make use of the DataRequirementsProcessor since that would require introducing a dependency on the elm-fhir package from the translator.
> Updated CQL translator version to 3.3.2

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
Support autoload of some Bundles. If the Bundle is a document, use the title from the Composition as the resource title in the IG.
This does not make a difference for any other resource type and is a better alternative to not having a title at all.
> When autoloading document Bundles, read title from Composition

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/CqlSubSystem.java
- Fixed CQL translator options format checks
Resolution for #822
> Update CQL Translator Format Options 

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/ValidationPresenter.java
The generation of the qa-eslintcompact.txt does not contain all the errors, warnings and informationals that are generated.
The ones that are called "linkerrors" were not present in the output.
We use this file to fill the problem window of visual code so that the user can just click on an error and is presented with the correct file and location automatically.
This pr completes this eslintcompact with that addtional information so that it is complete and contentwise identical to the other qa outputs. Now the total number of errors, warnings and informationals is correct with the summary given.
> FIX: The eslint text file does not contain all the error's, warnings and informationals.

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
As per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#technical_summary:
> Tag omission:	None, both the starting and ending tag are mandatory.
Does not fix #848 (yet), because the HTML is parsed and re-rendered wrongly by `XhtmlComposer`. Another patch in core is needed: https://github.com/hapifhir/org.hl7.fhir.core/pull/1553
> The button tag is not auto-closing

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java
I have scenarios where I'd like to style content differently, and selecting `<p>` without classes won't work. Is something like this viable?
---
Also, there may be a simpler way for me to accomplish what I want, which is to do something like
{% include StructureDefinition-cgm-data-submission-bundle-header.xhtml %}
...in my markdown pages without pulling in anything except the markdown description of my profile.
I still think assigning classes in generated HTML is a good idea though.
> Add classes to profile header content

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/DBBuilder.java
Add sqlToData templating
https://github.com/argonautproject/cgm/blob/a5b65a14639532e595702ed225642c95213e15d7/input/pagecontent/index.md?plain=1#L175-L214
```md
{% sqlToData mappingCodes SELECT
c.code as "Temporary Code",
CASE
WHEN cm.TargetCode IS NOT NULL THEN cm.TargetCode
ELSE 'No LOINC Available'
END as "LOINC Code"
FROM
Concepts c
JOIN Resources r ON c.ResourceKey = r.key
LEFT JOIN ConceptMappings cm ON c.code = cm.SourceCode AND cm.SourceSystem LIKE '%cgm-summary-codes-temporary'
WHERE
r.json->>'$.url' LIKE '%temporary'
%}
{% assign mappedCodes = 0 %}
{% assign unmappedCodes = 0 %}
{% for row in mappingCodes %}
{% if row["LOINC Code"] == "No LOINC Available" %}
{% assign unmappedCodes = unmappedCodes | plus: 1 %}
{% else %}
{% assign mappedCodes = mappedCodes | plus: 1 %}
{% endif …
```
> Add sqlToData templating

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/FSHRunner.java
- org.hl7.fhir.publisher.core/src/test/java/org/hl7/fhir/igtools/publisher/FSHRunnerTest.java
The previous implementation of MySushiHandler used a StringBuilder, which was trying to append the first byte value of a two-byte UTF-8 character, resulting in a silent failure.
Fix uses a ByteArrayOutputStream and also treats invalid characters b replacing them with '?'.
> Fix issues with UTF-8 2-byte characters

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/HistoryGenerator.java
In the ITI.MHD IG, the following fsh generated resource (ITI.MHD/fsh-generated/resources/Bundle-ex-response-comprehensiveProvideDocumentBundleComplete.json) causes a NullPointer exception when processed by HistoryGenerator.
```json
{
"resourceType": "Bundle",
"id": "ex-response-comprehensiveProvideDocumentBundleComplete",
"meta": {
"security": [
{
"code": "HTEST",
"system": "http://terminology.hl7.org/CodeSystem/v3-ActReason"
}
],
"profile": [
"https://profiles.ihe.net/ITI/MHD/StructureDefinition/IHE.MHD.ProvideDocumentBundleResponse"
]
},
"type": "transaction-response",
"link": [
{
"relation": "self",
"url": "http://example.com/fhir"
}
],
"entry": [
{
"response": {
"status": "201 Created",
"location": "List/501",
"lastModified": "2020-10-05T11:56:15.094+00:00"
}
},
{
"response": { …
```
> Fix nullpointer in HistoryGenerator

- checkstyle.xml
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/PackageReleaser.java
- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/TemplateReleaser.java
- pom.xml
There are already helper methods in place in XMLUtils to address potential XXE vulnerabilities.
This PR uses the checkstyle plugin to disallow instantiation of those various factories anywhere except where they are called in XMLUtils.
> Automate testing for XMLUtils factory methods

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
Java Locale toString returns the Java Constant representation of a locale instead of the correct BCP 47 language tag.
> Use BCP 47 language tag instead of Java Locale toString

- .github/workflows/docker.yml
- Dockerfile
- README.md
This supersedes this PR: https://github.com/HL7/fhir-ig-publisher/pull/97 initially created by @chgl.
After review, the Docker image in that PR refused to build. This PR fixes the issue by updating to a modern Jekyll install, and permits execution of common IG tasks with the build image.
Closes https://github.com/HL7/fhir-ig-publisher/issues/93
> To make this really useful, this repository should be connected to Docker Hub to automatically build and publish the container image.
This will follow; for now, the pipeline builds but does not yet push the image.
> Add Dockerfile

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java
Removes the overhead for translating the text log into html.
> Use HTML logging for terminology

- org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/CqlSubSystem.java
Incorrect behavior can be seen on this branch of the Opioid IG: https://github.com/cqframework/opioid-cds-r4/tree/2024-ig-eoy-update
> #1079: Fixed CqlSubsystem referencing included CQL libraries incorrectly

- build-and-exec-jobs-template.yml
Windows runners are failing to correctly install Jekyll, resulting in failed exec tests.
> Fix jekyll steps in exec tests on Windows

- .github/actions/build-and-cache-ig-publisher/action.yml
- .github/workflows/delta.yml
When running the QA Delta action, you can now include a branch of core to be used on building the IG Publisher. 
In the screencap below, the **IG Publisher Commit SHA** and **org.hl7.fhir.core Commit SHA** are both able to be set to branch names or commit hashes.
If **org.hl7.fhir.core Commit SHA** is left blank, org.hl7.fhir.core builds will be pulled from whatever is available on public maven repositories.
If **org.hl7.fhir.core Commit SHA** is a valid branch or commit, org.hl7.fhir.core will be built in the workflow and IG Publisher will use that version instead of attempting to download it.
> Allow QA Delta to run with branch of org.hl7.fhir.core
